### ISSUE TITLE
Consider exposing type for `jstz.olson.timezones`

### ISSUE THREAD

**Issue by tansongyang** [iansinnott/jstz#10]
I'm using TypeScript. My use case: We want to try to guess the user's timezone, but, if they want to change it, they can do so in a dropdown. TypeScript has ways of turning off type checking in certain scenarios, so I could just do that, but it would be convenient to have it officially exposed.

I'm willing to do a PR.

**Comment by iansinnott** [comment]
Yeah if you want to create a types file (`jstz.d.ts`?) I'd be happy to merge it in

**Comment by tansongyang** [comment]
Thanks! A types file already exists, so I'll just modify it.
