### ISSUE TITLE
MacOS - New Zealand/Auckland - Error on line 125

### ISSUE THREAD

**Issue by ghost** [iansinnott/jstz#21]
When I change my timezone to New Zealand/Auckland (or any New Zealand city) jstz crashes on line 125
`retval.timezone_name = tmp[0];`

TypeError: Cannot read property '0' of undefined

This is a cross browser issue.

**Comment by iansinnott** [comment]
Hey @pc-trent, can you provide repro steps?

**Comment by ghost** [comment]
Sorry for wasting your time. jstz has been cloned numerous times, I was using the bower version which is not this... It's a much much older original fork.

**Comment by iansinnott** [comment]
Gotcha. Thanks for closing this out @pc-trent.
